### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sfap** [MassiveCraft/MassiveTickets#11]
[14:59:56] [Server thread/ERROR]: Could not load 'plugins\MassiveTickets.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [Spigot.jar:git-Spigot-76236cb-62a2169]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [Spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [Spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot.jar:git-Spigot-76236cb-62a2169]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[14:59:56] [Server thread/ERROR]: Could not load 'plugins\MultiInv.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: TuxTwoLib

**Comment by ulumulu1510** [comment]
If you are reading the exception for a moment, you might have been able to recognise that MassiveTickets has an UnknownDependencyException: MassiveCore. This means, MassiveTickets requires MassiveCore to be installed.

Make sure you have MassiveCore installed, as all our plugins depend on it. Then, the error will resolve itself.
