### ISSUE TITLE
Could not load 'plugins\MassiveTickets.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by AgentCortez** [MassiveCraft/MassiveTickets#15]
```
[16:05:25] [Server thread/ERROR]: Could not load 'plugins\MassiveTickets.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-f9671b8-4d87c34]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-f9671b8-4d87c34]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-f9671b8-4d87c34]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-f9671b8-4d87c34]
```

**Comment by MarkehMe** [comment]
Hi! Please read the first line of your stack trace message.

```
Could not load 'plugins\MassiveTickets.jar' in folder 'plugins' 
org.bukkit.plugin.UnknownDependencyException: MassiveCore
```

An UnknownDependencyException means there is an unknown dependency. This being MassiveCore.

You can grab that here:
* https://dev.bukkit.org/bukkit-plugins/mcore/
* or https://www.spigotmc.org/resources/massivecore.1901/

Hope that helps.
